---

- name: Install docker
  yum:
    name: docker
    state: latest

- name: Create jenkins directory
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/jenkins

- name: Install docker pip
  pip:
    name: docker
    state: latest

- name: Start docker
  service:
      name: docker
      state: started

- name: Pull latest jenkins docker image
  docker_image:
     name: drewamido/jenkins

- name: Create and start a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: drewamido/jenkins
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - "/share/jenkins:/var/jenkins_home"
    state: started
    recreate: no


   






